### ISSUE TITLE
TypeError: logger.warn is not a function

### ISSUE THREAD

**Issue by Ra72xx** [Nerivec/ember-zli#6]
Using the tarball as provided in the releases section, I get the following error during many operations:

```
? Menu
  Join network
  Rejoin network
❯ Leave network
  Backup NVM3 tokens
  Restore NVM3 tokens
  Reset NVM3 tokens
- Get network info (disabled)file:///opt/ember-zli/dist/index.js:53
        logger.warn(getZHMessage(message), { namespace });
               ^

TypeError: logger.warn is not a function
    at Object.warning (file:///opt/ember-zli/dist/index.js:53:16)
    at UartAsh.onFrame (/opt/ember-zli/node_modules/zigbee-herdsman/dist/adapter/ember/uart/ash.js:425:33)
    at AshParser.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at AshParser._transform (/opt/ember-zli/node_modules/zigbee-herdsman/dist/adapter/ember/uart/parser.js:23:18)
    at Transform._write (node:internal/streams/transform:171:8)
    at writeOrBuffer (node:internal/streams/writable:570:12)
    at _write (node:internal/streams/writable:499:10)

Node.js v20.17.0

```

I use just the files as provided in the tarball, Ubuntu 24.04 with no local NodeJS installed. Other functions work, e.g. I was able to perform a firmware update.

**Comment by Nerivec** [comment]
Should be fixed in 2.6.1 👍
