### ISSUE TITLE
Cant Update Firmware on SLZB-07 on Windows

### ISSUE THREAD

**Issue by Kentrath** [Nerivec/ember-zli#9]
I was able to update last week. Now i want to change the firmware and get issues. ZLI is the newest 2.9.1
```
Node.js v20.18.0
PS C:\> ember-zli bootloader
[2024-11-20 04:10:35.246] info:         cli: Data folder: C:\Users\Alexander\ember-zli.
√ Path: COM10, Baudrate: 115200, RTS/CTS: true. Use this config? yes
√ Adapter model SMLight SLZB07
[2024-11-20 04:10:40.478] info:         gecko: Connecting to bootloader...
[2024-11-20 04:10:40.480] info:         gecko: Trying to enter bootloader...
[2024-11-20 04:10:40.528] info:         transport: Serial port opened
[2024-11-20 04:10:43.558] info:         transport: Closing serial connection...
[2024-11-20 04:10:43.567] info:         transport: Transport closed.
[2024-11-20 04:10:43.569] info:         gecko: Unable to enter bootloader.
[2024-11-20 04:10:43.569] info:         gecko: Connected to bootloader.
√ Menu Update firmware
√ Firmware source Use pre-defined firmware (using
https://github.com/Nerivec/ember-zli/raw/refs/heads/main/firmware-links.json)
√ Firmware version Latest from manufacturer
[2024-11-20 04:10:49.236] info:         cli: Downloading firmware from https://github.com/darkxst/silabs-firmware-builder/releases/download/20241106/slzb07_zigbee_ncp_8.0.2.0_115200.gbl.
[2024-11-20 04:10:50.192] info:         gecko: Firmware file metadata: {"baudrate":115200,"ezsp_version":"8.0.2.0","fw_type":"zigbee_ncp","fw_variant":null,"metadata_version":2,"sdk_version":"2024.6.2"}
√ Version: 8.0.2.0, Baudrate: 115200. Proceed with this firmware? yes
[2024-11-20 04:10:53.297] error:        gecko: Timed out waiting for UPLOADING after 1500ms.
C:\Users\Alexander\AppData\Roaming\npm\node_modules\ember-zli\node_modules\@oclif\core\lib\errors\exit.js:6
    throw new exit_1.ExitError(code);
    ^

ExitError: EEXIT: 1
    at Object.exit (C:\Users\Alexander\AppData\Roaming\npm\node_modules\ember-zli\node_modules\@oclif\core\lib\errors\exit.js:6:11)
    at Bootloader.exit (C:\Users\Alexander\AppData\Roaming\npm\node_modules\ember-zli\node_modules\@oclif\core\lib\command.js:183:16)
    at GeckoBootloader.<anonymous> (file:///C:/Users/Alexander/AppData/Roaming/npm/node_modules/ember-zli/dist/commands/bootloader/index.js:51:18)
    at GeckoBootloader.emit (node:events:519:28)
    at Timeout._onTimeout (file:///C:/Users/Alexander/AppData/Roaming/npm/node_modules/ember-zli/dist/utils/bootloader.js:520:30)
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7) {
  code: 'EEXIT',
  oclif: { exit: 1 },
  skipOclifErrorHandling: undefined,
  suggestions: undefined
}
```

**Comment by Nerivec** [comment]
Seems it's currently in a weird state.

Try using `ember-zli bootloader`, then `Exit bootloader (run firmware)` then back to `ember-zli bootloader` and try to flash again. That should cycle it in/out of bootloader.
You can also try unplugging your adapter for a few seconds, then plug it back in. It should do the same.
